trigger:
  branches:
    include:
      - main  # Change as per your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Set your Terraform working directory if it's not the root
  terraformWorkingDirectory: './terraform' 

  # Set Azure service connection name
  azureServiceConnection: 'your-azure-rm-service-connection'

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.11.4'

  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      workingDirectory: $(terraformWorkingDirectory)
      inlineScript: |
        echo "##[section]Terraform Init"
        terraform init \
          -backend-config="resource_group_name=<your-rg>" \
          -backend-config="storage_account_name=<your-storage-account>" \
          -backend-config="container_name=<your-container>" \
          -backend-config="key=<your-tfstate-file>.tfstate"

        echo "##[section]Terraform Validate"
        terraform validate

        echo "##[section]Terraform Plan"
        terraform plan -out=tfplan

        echo "##[section]Terraform Apply"
        terraform apply -auto-approve tfplan