trigger: none

parameters:
  - name: action
    displayName: Select Terraform Action
    type: string
    default: plan
    values:
      - plan
      - apply

variables:
  TF_VAR_resource_group_name: "my-tf-rg"
  TF_VAR_location: "East US"

stages:
  - stage: Terraform
    displayName: "Terraform ${{ parameters.action }}"
    jobs:
      - job: terraform
        displayName: "Run Terraform ${{ parameters.action }}"
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Initializing Terraform..."
                terraform init

                echo "Running Terraform ${{ parameters.action }}..."
                if [ "${{ parameters.action }}" == "plan" ]; then
                  terraform plan \
                    -var="resource_group_name=$TF_VAR_resource_group_name" \
                    -var="location=$TF_VAR_location"
                elif [ "${{ parameters.action }}" == "apply" ]; then
                  terraform apply -auto-approve \
                    -var="resource_group_name=$TF_VAR_resource_group_name" \
                    -var="location=$TF_VAR_location"
                fi
