name: Build and Push to ACR

on:
  push:
    paths:
      - '.github/workflows/ACR.yml'

jobs:  
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set ACR login server
        id: acr
        run: |
          ACR_NAME="myacr103085"
          echo "ACR_LOGIN_SERVER=${ACR_NAME}.azurecr.io" >> $GITHUB_ENV

      - name: Azure CLI - Login to ACR
        run: |
          az acr login --name myacr103085

      - name: Build and Push Docker image
        run: |
          IMAGE_TAG=${{ env.ACR_LOGIN_SERVER }}/nginx:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker build . --file Dockerfile --tag $IMAGE_TAG
          docker push $IMAGE_TAG
