name: Workflow A

on:
  push:
    paths:
      - '.github/workflows/docker.yml'
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag patrick-nginx-image:$(date +%s)


    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: pbisht2017/patrick-nginx-image:latest
   

  pull-docker-image:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Pull image from Docker Hub
        run: docker pull pbisht2017/patrick-nginx-image:latest

      - name: Run the image (optional)
        run: |
          docker run -d --name nginx-test -p 8080:80 pbisht2017/patrick-nginx-image:latest
          sleep 5
          docker ps
