name: Pull Docker Image

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

jobs:
  pull-image:
    runs-on: ubuntu-latest

    steps:
      - name: Pull image from Docker Hub
        run: docker pull pbisht2017/prateek-nginx-image:latest

      - name: Run the image (optional)
        run: |
          docker run -d --name nginx-test -p 8080:80 pbisht2017/prateek-nginx-image:latest
          sleep 5
          docker ps
