name: Create Azure container registry

on:
  workflow_dispatch:

jobs:
  create-acr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create \
            --name myrg \
            --location eastus

      - name: Create Azure Container Registry
        run: |
          az acr create \
            --resource-group myrg \
            --name myacr103085 \
            --sku Basic \
            --admin-enabled true

      - name: Create App Service Plan
        run: |
          az appservice plan create \
            --name myAppServicePlan103085 \
            --resource-group myrg \
            --sku B1 \
            --is-linux

      - name: Create Web App
        run: |
          az webapp create \
            --resource-group myrg \
            --plan myAppServicePlan103085 \
            --name my-app-service-103085 \
            --runtime "PYTHON:3.10" \
            --deployment-local-git
